import os
from typing import Dict, Any, List, Optional
from rich.text import Text
from textual import on
from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Horizontal, Vertical, VerticalScroll
from textual.screen import ModalScreen
from textual.widgets import Static

SUBAGENT_CHAT_CSS = """
SubagentChatModal {
    background: #090d13;
    color: #c9d1d9;
}

#subagent-chat-scroll {
    width: 100%;
    height: 1fr;
    padding: 1 2;
    scrollbar-size-vertical: 1;
    scrollbar-color: #30363d;
}

.subagent-user-box {
    width: 100%;
    height: auto;
    background: #161b22;
    padding: 1 2;
    margin-bottom: 1;
    border: none;
}

.subagent-agent-box {
    width: 100%;
    height: auto;
    background: #0d1117;
    padding: 1 2;
    margin-bottom: 1;
    border: none;
}

#subagent-system-prompt-dock {
    dock: bottom;
    height: auto;
    max-height: 12;
    background: #161b22;
    border-top: solid #21262d;
    padding: 1 2;
}

#subagent-system-header-row {
    width: 100%;
    height: 1;
    margin-bottom: 1;
}

#subagent-system-header {
    width: 1fr;
    color: #8b949e;
    text-style: bold;
}

#subagent-system-meta {
    width: auto;
    color: #8b949e;
}

#subagent-system-body {
    width: 100%;
    height: auto;
    color: #c9d1d9;
}
"""

class SubagentChatModal(ModalScreen[None]):
    """Read-only chat interface for inspecting an autonomous subagent's execution,
    matching normal chat appearance (no top panel, no side pipe borders),
    with the Lead Agent generated System Prompt displayed in the bottom dock,
    and agent indicator + esc exit displayed on the right side."""

    CSS = SUBAGENT_CHAT_CSS

    BINDINGS = [
        Binding("escape", "dismiss_modal", "Close"),
        Binding("ctrl+q", "dismiss_modal", "Close"),
    ]

    def __init__(
        self,
        role: str,
        goal: str,
        system_prompt: str,
        history: Optional[List[Dict[str, Any]]] = None,
        findings: Optional[List[str]] = None,
        agent_index: int = 1,
        agent_total: int = 1,
        **kwargs
    ):
        super().__init__(**kwargs)
        self.role_name = role
        self.goal = goal
        self.system_prompt_text = system_prompt
        self.chat_history = history or []
        self.findings = findings or []
        self.agent_index = agent_index
        self.agent_total = agent_total

    def compose(self) -> ComposeResult:
        with VerticalScroll(id="subagent-chat-scroll"):
            with Vertical(classes="subagent-user-box"):
                yield Static("[bold #58a6ff]user[/]\n" + self.goal)

            with Vertical(classes="subagent-agent-box"):
                header_text = f"[bold #58a6ff]⌬[/]  [bold #e6edf3]{self.role_name}[/] [dim](Subagent)[/]"
                yield Static(header_text)
                if self.chat_history:
                    for turn in self.chat_history:
                        r = turn.get("role", "")
                        c = turn.get("content", "")
                        if r == "assistant":
                            yield Static(f"\n{c}")
                else:
                    body = f"\nTask goal completed: {self.goal}\n"
                    if self.findings:
                        body += "\nKey findings:\n" + "\n".join(f"- {f}" for f in self.findings)
                    yield Static(body)

        with Vertical(id="subagent-system-prompt-dock"):
            with Horizontal(id="subagent-system-header-row"):
                yield Static("SYSTEM PROMPT (AUTONOMOUSLY GENERATED BY LEAD AGENT):", id="subagent-system-header")
                yield Static(f"Agent {self.agent_index} of {self.agent_total} · esc exit", id="subagent-system-meta")
            yield Static(self.system_prompt_text, id="subagent-system-body")

    def action_dismiss_modal(self) -> None:
        self.dismiss()
