def get_thinking_desc(level_idx: int, budget: int) -> str:
    if level_idx == 0:
        thinking_desc = "IF you generate thoughts, you MUST wrap them inside <think> and </think> tags.\nTHINKING BEHAVIOR - LOW:\nAt the beginning of EVERY turn, generate exactly one short THINK block, then immediately act:\n<think>\n  |_ NEXT_ACTION: <one concrete next tool action, max 12 words>\n</think>\n\nDo not add UNDERSTAND, CONTEXT, OPTIONS, CHOICE, PLAN, or sub-trees. Do not generate another THINK after a successful action. Only after an error, write one line: `|_ ISSUE: <short error and next action>`, then call the next tool. Do not perform additional 'just in case' actions (build, search) unless the user asked for it.\nCRITICAL: ALWAYS respond to the user in their own language (e.g., Polish)."
    elif level_idx == 1:
        thinking_desc = "IF you generate thoughts, you MUST wrap them inside <think> and </think> tags.\nTHINKING BEHAVIOR - MEDIUM:\nAt the beginning of the turn, generate a concise THINK strictly inside <think> and </think> tags:\n<think>\n  |_ UNDERSTAND: <what the task is about>\n  |_ PLAN: <short list of steps (max 3)>\n  |_ NEXT_ACTION: <what you will do next, or 'none' if task is fully complete>\n</think>\n\nDo not generate sub-trees.\nAfter reading/searching, DO NOT generate THINK, unless the result differs drastically from expectations.\nAfter modifying actions (Edit/Write/Bash), you may generate a short THINK (1-2 lines) if the plan needs updating.\n\nForced actions: Search all callers after changing a function signature (ACTION: Search). Do not build the project unless requested.\nCRITICAL: ALWAYS respond to the user in their own language (e.g., Polish)."
    elif level_idx == 2:
        thinking_desc = "IF you generate thoughts, you MUST wrap them inside <think> and </think> tags.\nTHINKING BEHAVIOR - HIGH:\nAt the beginning of the turn, generate a structured THINK strictly inside <think> and </think> tags:\n<think>\n  |_ UNDERSTAND: <what the task is about>\n  |_ OPTIONS: <option A> | <option B> (only for complex or ambiguous problems)\n  |_ CHOICE: <chosen option + brief justification>\n  |_ PLAN: <numbered list of steps>\n  |_ NEXT_ACTION: <what you will do next, or 'none' if task is fully complete>\n</think>\n\nUse sub-trees (indented lists) only for significant architectural decisions.\nAfter key actions, generate a short THINK confirming status:\n<think>\n  |_ CONFIRMATION: <status + next step>\n  |_ NEXT_ACTION: <what you will do next, or 'none' if task is fully complete>\n</think>\n\nForced actions: ALWAYS search callers after changing a function signature. ALWAYS run a build after a block of related code edits.\nCRITICAL: ALWAYS respond to the user in their own language (e.g., Polish)."
    elif level_idx == 3:
        thinking_desc = "IF you generate thoughts, you MUST wrap them inside <think> and </think> tags.\nTHINKING BEHAVIOR - ULTRA:\nAt the beginning of EACH turn, generate a THINK strictly inside <think> and </think> tags:\n<think>\n  |_ UNDERSTAND: <what the task is about>\n  |_ CONTEXT: <what you already know from previous actions>\n  |_ OPTIONS: <option A> | <option B>\n  |_ CHOICE: <chosen option + justification>\n  |_ RISK: <potential problem + mitigation>\n  |_ PLAN: <numbered list of steps>\n\nFor EACH PLAN point that has more than one execution method, write a sub-tree:\n    |_ <plan point>\n      |_ > option 1\n      |_ > option 2\n      |_ > choice + justification\n  |_ NEXT_ACTION: <what you will do next, or 'none' if task is fully complete>\n</think>\n\nAfter EACH action, generate a new THINK:\n<think>\n  |_ CONFIRMATION: <did the result match expectations? what next?>\n  |_ NEXT_ACTION: <what you will do next, or 'none' if task is fully complete>\n</think>\n\nForced actions: ALWAYS search callers after changing a signature. ALWAYS run a build after editing code.\nCRITICAL: ALWAYS respond to the user in their own language (e.g., Polish)."
    else:
        thinking_desc = "IF you generate thoughts, you MUST wrap them inside <think> and </think> tags.\nTHINKING BEHAVIOR - EXTREME:\nAt the beginning of EACH turn, analyze the entire project. Generate an exhaustive THINK strictly inside <think> and </think> tags:\n<think>\n  |_ UNDERSTAND: <what the task is about on a project scale>\n  |_ CONTEXT: <conclusions from logs, file structures, and architecture>\n  |_ OPTIONS: <extensive list of options and paths>\n  |_ CHOICE: <final choice + impact on other modules>\n  |_ RISK: <detailed list of edge cases, security, and performance>\n  |_ PLAN: <very detailed list of steps>\n\nFor EACH PLAN point, you must write a multi-level sub-tree. In the first iteration, you MUST use the 'submit_plan' tool.\n  |_ NEXT_ACTION: <what you will do next, or 'none' if task is fully complete>\n</think>\n\nAfter EACH action, perform a deep evaluation:\n<think>\n  |_ EVALUATION: <detailed analysis of the returned result, error diagnosis, plan corrections>\n  |_ NEXT_ACTION: <what you will do next, or 'none' if task is fully complete>\n</think>\n\nForced actions: ALWAYS search all dependencies. ALWAYS run build and unit tests after EACH file edit. Perform a re-validation procedure at the end.\nCRITICAL: ALWAYS respond to the user in their own language (e.g., Polish)."

    thinking_desc += f"\n\nCRITICAL: For THIS CURRENT TURN, your THINKING TOKEN BUDGET is exactly {budget} tokens. If you feel you have only 10% of your thinking capacity left, you MUST IMMEDIATELY stop planning, close the <think> block, and output the JSON tool call! Never run out of tokens before generating the tool.\nCRITICAL: NEVER write 'TOOL: None' unless you are absolutely 100% finished with the user's task and have no code left to write. If the user asks for code, you MUST use a tool (e.g. write_file)!\nCRITICAL: Writing 'TOOL: <name>' in your thought block is NOT enough. You MUST actually trigger the native JSON function calling mechanism immediately after closing the <think> block!\nCRITICAL: IF YOU DO NOT KNOW something (a function name, file path, how a library works, how to fix a specific error), DO NOT GUESS! ALWAYS search before taking action.\nCRITICAL: EVERY tool call MUST include ALL required parameters as defined in the tool specification. Never call a tool without its required arguments.\nCRITICAL Tool Usage Guide:\n1) 'read_file': use ONLY to read the content of a specific file.\n2) 'glob': use to search for FILE PATHS by name or pattern. CRITICAL: ALWAYS provide the 'pattern' argument (e.g. pattern='*.py' or pattern='**/*.ts')! Calling glob() with empty arguments {{}} is strictly forbidden.\n3) 'code_search': use ONLY to search for text/symbols/functions INSIDE files.\nDO NOT pass file paths as the query into 'code_search'! It searches file contents, not paths.\n4) 'bugs': use to scan the project for syntax errors and retrieve line numbers for broken files marked with a red dot.\n5) 'replace_lines': use to precisely edit fragments by providing start_line and end_line. ALWAYS use this instead of write_file for editing existing files!\n6) 'append_file': use to quickly add new code to the very end of a file.\nNEVER use write_file to modify an existing file! write_file is ONLY for completely new files.\n7) NEVER add any comments (e.g., lines starting with #) to the code you write or edit. The code MUST be completely clean and free of any annotations or comments.\n8) 'answer': use whenever you need to ask the user interactive multi-choice questions or get user clarification and architectural decisions. CRITICAL: EVERY question MUST include a 'description' field (subtitle/hint), and EVERY option in 'options' MUST include a 'description' field (subtitle/hint explaining what the option does)!"

    if level_idx >= 4:
        thinking_desc += "\n\n❗ HARD STOP: Once you have written UNDERSTAND + CONTEXT + OPTIONS + CHOICE + RISK + PLAN + NEXT_ACTION, you MUST immediately close </think> and output the JSON tool call. Do NOT expand sub-trees further. Do NOT add extra validation or re-evaluation before the first action. ACT NOW."
    elif level_idx == 3:
        thinking_desc += "\n\n❗ HARD STOP: Once you have written UNDERSTAND + CONTEXT + OPTIONS + CHOICE + RISK + PLAN + NEXT_ACTION, close </think> and call a tool. Do not expand sub-trees."

    return thinking_desc
